export const MM_PER_INCH = 25.4;
export const PAPER_SIZES_MM = {
  A4:     [210.0, 297.0],
  A5:     [148.0, 210.0],
  A6:     [105.0, 148.0],
  Rezept: [105.0, 148.0],
  Letter: [215.9, 279.4],
};

export const PROFILES = {
  epson_fx:          { label: "Epson FX-80",      pins: 9,  dpi_h: 120, dpi_v: 72,  dot_diameter_mm: 0.35, dot_softness: 0.30, ink_density: 0.88, passes: 1, jitter_mm: 0.040, banding: 0.08, supports_condensed: true  },
  epson_lq:          { label: "Epson LQ-850",     pins: 24, dpi_h: 180, dpi_v: 180, dot_diameter_mm: 0.20, dot_softness: 0.22, ink_density: 0.82, passes: 1, jitter_mm: 0.020, banding: 0.04, supports_condensed: true  },
  ibm_proprinter:    { label: "IBM Proprinter",   pins: 9,  dpi_h: 120, dpi_v: 72,  dot_diameter_mm: 0.38, dot_softness: 0.26, ink_density: 0.95, passes: 2, jitter_mm: 0.050, banding: 0.10, supports_condensed: false },
  oki_microline:     { label: "OKI Microline",    pins: 9,  dpi_h: 144, dpi_v: 72,  dot_diameter_mm: 0.33, dot_softness: 0.34, ink_density: 0.85, passes: 1, jitter_mm: 0.035, banding: 0.12, supports_condensed: true  },
  star_nx1000:       { label: "Star NX-1000",     pins: 9,  dpi_h: 144, dpi_v: 144, dot_diameter_mm: 0.32, dot_softness: 0.28, ink_density: 0.87, passes: 1, jitter_mm: 0.030, banding: 0.07, supports_condensed: true  },
  panasonic_kx:      { label: "Panasonic KX-P",   pins: 24, dpi_h: 360, dpi_v: 180, dot_diameter_mm: 0.22, dot_softness: 0.20, ink_density: 0.88, passes: 1, jitter_mm: 0.020, banding: 0.04, supports_condensed: true  },
  dec_la75:          { label: "DEC LA75",          pins: 9,  dpi_h: 144, dpi_v: 144, dot_diameter_mm: 0.35, dot_softness: 0.25, ink_density: 0.90, passes: 1, jitter_mm: 0.020, banding: 0.05, supports_condensed: false },
  nec_p6:            { label: "NEC P6",            pins: 24, dpi_h: 360, dpi_v: 360, dot_diameter_mm: 0.15, dot_softness: 0.15, ink_density: 0.85, passes: 1, jitter_mm: 0.015, banding: 0.03, supports_condensed: true  },
  commodore_mps:     { label: "MPS-803",           pins: 7,  dpi_h: 60,  dpi_v: 72,  dot_diameter_mm: 0.45, dot_softness: 0.40, ink_density: 0.80, passes: 1, jitter_mm: 0.080, banding: 0.15, supports_condensed: false },
  apple_imagewriter: { label: "ImageWriter II",    pins: 9,  dpi_h: 144, dpi_v: 72,  dot_diameter_mm: 0.35, dot_softness: 0.25, ink_density: 0.85, passes: 1, jitter_mm: 0.030, banding: 0.06, supports_condensed: true  },
};

export const WEAR_PATTERNS = {
  cloudy:               { label: "Cloudy",       desc: "Blotchy ink density, ribbon saturation spots" },
  ghosting:             { label: "Ghosting",      desc: "Bi-directional print shadow at row offset" },
  misaligned:           { label: "Wobble",        desc: "Horizontal row drift, worn carriage rails" },
  pin_skip:             { label: "Pin Skip",      desc: "Dead/weak pin leaves horizontal void lines" },
  smudge:               { label: "Smudge",        desc: "Paper-contact drag in intermittent bands" },
  ribbon_twist:         { label: "Ribbon Twist",  desc: "Twisted ribbon, column-wise density variation" },
  head_gap:             { label: "Head Gap",      desc: "Platen too wide, all dots print too light" },
  ink_starved:          { label: "Ink Starved",   desc: "Ribbon near end, density fades line by line" },
  paper_slip:           { label: "Paper Slip",    desc: "Feed roller slip, irregular line spacing" },
  static_noise:         { label: "Static",        desc: "Electrostatic discharge, stray dot bursts" },
  double_feed:          { label: "Double Feed",   desc: "Two sheets stacked, faint offset shadow copy" },
  mechanical_resonance: { label: "Resonance",     desc: "Print head vibration, wavy vertical tracks" },
};

export const SYSTEM_PRESETS = [
  {
    id: "rezept", name: "Rezept", system: true,
    profile: "oki_microline",
    brightness: 100, contrast: 100, gamma: 2.0,
    dither: "ordered", threshold: 128,
    ink: [25, 25, 30], paper: null,
    paperFormat: "Original", orientation: "Portrait",
    doubleStrike: false, condensed: false,
    dpi: 300, jitterScale: 0.0, bandingScale: 0.0, maxSize: 8000,
    wearLayers: [{ pattern: "misaligned", strength: 15 }, { pattern: "ghosting", strength: 20 }],
    seed: 0, softBlur: false, invert: false,
  },
  {
    id: "photo", name: "Photo", system: true,
    profile: "epson_lq",
    brightness: 0, contrast: 20, gamma: 1.1,
    dither: "floyd_steinberg", threshold: 128,
    ink: [25, 25, 30], paper: null,
    paperFormat: "Original", orientation: "Portrait",
    doubleStrike: false, condensed: false,
    dpi: 300, jitterScale: 0.8, bandingScale: 0.5, maxSize: 8000,
    wearLayers: [{ pattern: "cloudy", strength: 30 }],
    seed: 0, softBlur: false, invert: false,
  },
  {
    id: "worn_receipt", name: "Worn Receipt", system: true,
    profile: "star_nx1000",
    brightness: 10, contrast: 25, gamma: 1.2,
    dither: "ordered", threshold: 140,
    ink: [40, 32, 20], paper: [248, 245, 232],
    paperFormat: "Original", orientation: "Portrait",
    doubleStrike: false, condensed: false,
    dpi: 300, jitterScale: 1.2, bandingScale: 0.8, maxSize: 8000,
    wearLayers: [
      { pattern: "ribbon_twist", strength: 55 },
      { pattern: "ink_starved",  strength: 40 },
      { pattern: "pin_skip",     strength: 20 },
    ],
    seed: 0, softBlur: false, invert: false,
  },
  {
    id: "c64", name: "C64 Label", system: true,
    profile: "commodore_mps",
    brightness: 5, contrast: 30, gamma: 1.0,
    dither: "ordered", threshold: 128,
    ink: [20, 45, 130], paper: [248, 245, 232],
    paperFormat: "Original", orientation: "Portrait",
    doubleStrike: true, condensed: false,
    dpi: 300, jitterScale: 1.5, bandingScale: 1.2, maxSize: 8000,
    wearLayers: [{ pattern: "pin_skip", strength: 25 }, { pattern: "smudge", strength: 20 }],
    seed: 42, softBlur: false, invert: false,
  },
  {
    id: "crisp", name: "Crisp", system: true,
    profile: "nec_p6",
    brightness: 0, contrast: 30, gamma: 1.0,
    dither: "threshold", threshold: 128,
    ink: [25, 25, 30], paper: [255, 255, 255],
    paperFormat: "Original", orientation: "Portrait",
    doubleStrike: false, condensed: false,
    dpi: 300, jitterScale: 0.3, bandingScale: 0.2, maxSize: 8000,
    wearLayers: [],
    seed: 0, softBlur: false, invert: false,
  },
  {
    id: "ghost_doc", name: "Ghost Doc", system: true,
    profile: "ibm_proprinter",
    brightness: -10, contrast: 15, gamma: 1.3,
    dither: "ordered", threshold: 128,
    ink: [25, 25, 30], paper: null,
    paperFormat: "Original", orientation: "Portrait",
    doubleStrike: false, condensed: false,
    dpi: 300, jitterScale: 0.8, bandingScale: 1.0, maxSize: 8000,
    wearLayers: [
      { pattern: "ghosting",             strength: 45 },
      { pattern: "double_feed",          strength: 30 },
      { pattern: "mechanical_resonance", strength: 25 },
    ],
    seed: 0, softBlur: true, invert: false,
  },
  {
    id: "archive", name: "Archive", system: true,
    profile: "epson_fx",
    brightness: -5, contrast: 10, gamma: 1.4,
    dither: "ordered", threshold: 145,
    ink: [35, 28, 18], paper: [234, 223, 184],
    paperFormat: "Original", orientation: "Portrait",
    doubleStrike: false, condensed: false,
    dpi: 300, jitterScale: 1.0, bandingScale: 1.0, maxSize: 8000,
    wearLayers: [
      { pattern: "ink_starved", strength: 50 },
      { pattern: "head_gap",    strength: 30 },
      { pattern: "paper_slip",  strength: 20 },
    ],
    seed: 0, softBlur: false, invert: false,
  },
];

export const state = {
  profile: "oki_microline",
  dither: "threshold",
  threshold: 128,
  ink: [25, 25, 30],
  paper: [255, 255, 255],
  paperFormat: "Original",
  orientation: "Portrait",
  doubleStrike: false,
  condensed: false,
  brightness: 0,
  contrast: 20,
  gamma: 1.0,
  invert: false,
  dpi: 300,
  jitterScale: 1.0,
  bandingScale: 1.0,
  maxSize: 8000,
  wearLayers: [],
  seed: 0,
  softBlur: false,
  sourceImage: null,
};
